[theme]
base = "light"
primaryColor = "#1e50a0"
backgroundColor = "#e9edf4"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f1b2d"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
